---
- name: Setting up System
  hosts: ec2
  connection: ssh
  become: true

  tasks:
  - name: Install aptitude using apt
    apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

  - name: Install required system packages
    apt: name={{ item }} state=latest update_cache=yes
    loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present

  - name: Update apt and install docker-ce
    apt: update_cache=yes name=docker-ce state=latest

  - name: Install Docker Module for Python
    pip:
      name: docker

  - name: adding existing user to group docker and sudo
    user:
      name: ubuntu
      groups: docker,root
      append: yes

  - name: Change file permissions
    ansible.builtin.file:
      path: /var/run/docker.sock
      mode: '0666'

  - name: Docker Run
    command: docker run -d -p 8080:8080 --name con ziwei0/awsdevops