---
- name: Setting up System
  hosts: ec2
  connection: ssh
  become: true

  tasks:
  - name: Update the machine
    command: apt update

  - name: Installing docker
    command: apt install docker* -y

  - name: Adding user to group
    command: usermod -aG docker ${USER}

#  - name: adding existing user '{{ user }}' to group docker and sudo
#    user:
#      name: '{{ user }}'
#      groups: docker,root
#      append: yes

  - name: Changing permission
    command: chmod 666 /var/run/docker.sock

#  - name: Change file ownership, group and permissions
#    ansible.builtin.file:
#      path: /var/run/docker.sock
#      mode: '0666'

  - name: Modify User Account
    command: usermod -aG root $USER

  - name: Modify User Account
    command: service docker restart
    
  - name: Docker Run
    command: docker run -d -p 8080:8080 --name con ziwei0/awsdevops
