---
- name: Setting up System
  hosts: ec2
  connection: ssh
  become: true

  tasks:
  - name: Update the machine
    command: apt update

  - name: Installing docker
    command: apt install docker* -y

  - name: Adding user to group
    command: sudo usermod -aG docker ${USER}

  - name: Changing permission
    command: sudo chmod 666 /var/run/docker.sock

  - name: Modify User Account
    command: sudo usermod -G root $USER
  
  - name: Docker Run
    command: docker run -d -p 8080:8080 --name con ziwei0/awsdevops
